# This workflow will install Python dependencies, run tests and lint with a 
# single version of Python
# For more information see: 

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        export PATH="$HOME/.poetry/bin:$PATH"
        source $HOME/.poetry/env
    - name: echo PATH
      run: echo $PATH
    - name: Poetry version
      run: poetry --version
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      run: |
        poetry shell
        pytest
